;(SECTION 6 8)
;(test #t vector? '#(0 (2 2 2 2) "Anna"))
;(test #t vector? '#())
;(test '#(a b c) vector 'a 'b 'c)
;(test '#() vector)
;(test 3 vector-length '#(0 (2 2 2 2) "Anna"))
;(test 0 vector-length '#())
;(test 8 vector-ref '#(1 1 2 3 5 8 13 21) 5)
;(test '#(0 ("Sue" "Sue") "Anna") 'vector-set
;	(let ((vec (vector 0 '(2 2 2 2) "Anna")))
;	  (vector-set! vec 1 '("Sue" "Sue"))
;	  vec))
;(test '#(hi hi) make-vector 2 'hi)
;(test '#() make-vector 0)
;(test '#() make-vector 0 'a)
